#!/bin/bash
# Quick Deploy Script for Streamlit Cloud

echo "🚀 Solana Wallet Tracker - Quick Deploy to Streamlit Cloud"
echo "==========================================================="
echo ""
echo "Step 1: Make sure your code is on GitHub"
echo "Step 2: Go to https://share.streamlit.io"
echo "Step 3: Sign in with GitHub"
echo "Step 4: Click 'New app'"
echo ""
echo "Fill in these details:"
echo "  Repository: [Your GitHub username]/WalletTracker"
echo "  Branch: main (or your branch name)"
echo "  Main file path: web_app.py"
echo ""
echo "Click 'Deploy'!"
echo ""
echo "Your link will be:"
echo "  https://[username]-wallettracker-main.streamlit.app"
echo ""
echo "🎉 Share this link with anyone!"
echo ""
echo "========================================================="
echo "Need help? Check DEPLOY_INSTRUCTIONS.md"
